app:
  title: Backstage - InfraWallet
  baseUrl: http://${INFRAWALLET_DOMAIN}

backend:
  baseUrl: http://${INFRAWALLET_DOMAIN}
  infraWallet:
    metricProviders:
      mock:
        - name: mock-metric-provider
    integrations:
      mock:
        - name: mock-integration

infraWallet:
  settings:
    defaultGroupBy: none
    defaultShowLastXMonths: 6
    readOnly: false
