name: Build and Deploy Packages to NPM

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths-ignore:
      - '**/docs/**'
      - '**.md'

permissions:
  contents: read

jobs:
  build-and-publish-to-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      #############################################################################
      # common steps
      #############################################################################

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth
      - name: yarn install
        run: |
          yarn install

      - name: validate config
        run: yarn backstage-cli config:check --lax

      - name: lint
        run: yarn backstage-cli repo lint

      - name: type checking and declarations
        run: yarn tsc:full

      - name: build
        run: yarn workspaces foreach -v --no-private run build

      - name: verify type dependencies
        run: yarn lint:type-deps

      #############################################################################
      # publish a release candidate to npm
      #############################################################################
      - name: (for rc) change infrawallet version to `semver-datetime-sha`
        if: github.event_name == 'push'
        working-directory: ./plugins/infrawallet
        run: |
          VERSION=$(npm pkg get version --workspaces=false | tr -d \")
          npm pkg set version=$VERSION-$(date +%F%T | tr -d '\-:')-$(echo ${{ github.sha }} | cut -c 1-7)

      - name: (for rc) change infrawallet-backend version to `semver-datetime-sha`
        if: github.event_name == 'push'
        working-directory: ./plugins/infrawallet-backend
        run: |
          VERSION=$(npm pkg get version --workspaces=false | tr -d \")
          npm pkg set version=$VERSION-$(date +%F%T | tr -d '\-:')-$(echo ${{ github.sha }} | cut -c 1-7)

      - name: (for rc) publish release candidate
        if: github.event_name == 'push'
        run: |
          yarn config set -H 'npmAuthToken' "${{secrets.NPM_TOKEN}}"
          yarn workspaces foreach -v --no-private npm publish --access public --tolerate-republish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      #############################################################################
      # publish a release to npm
      #############################################################################
      - name: publish release
        if: github.event_name == 'release'
        run: |
          yarn config set -H 'npmAuthToken' "${{secrets.NPM_TOKEN}}"
          yarn workspaces foreach -v --no-private npm publish --access public --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
